// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

// Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
// Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
// Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
// It can be verified that T285 = P165 = H143 = 40755.

// Find the next triangle number that is also pentagonal and hexagonal.

// Save Tt, t, Pp, p, Hh, h

package main

import (
	"fmt"
)

func penta(n int64) int64 {
	return n * ((3 * n) - 1) / 2
}

func tri(n int64) int64 {
	return n * (n + 1) / 2
}

func hexa(n int64) int64 {
	return n * ((2 * n) - 1)
}

func main() {

	t := int64(285)
	tt := tri(t)
	p := int64(165)
	pp := penta(p)
	h := int64(143)
	hh := hexa(h)

	target := int64(40756)

	for {

		for hh < target {
			h++
			hh = hexa(h)
		}
		if hh > target {
			target = hh
		}

		for pp < target {
			p++
			pp = penta(p)
		}
		if pp > target{
			target = pp
		}

		for tt < target {
			t++
			tt = tri(t)
		}
		if tt > target{
			target = tt
		}

		if tt == pp && pp == hh {
			break
		}
	}
	fmt.Println(tt)
}
